export type BcCustomer = {
  addressLine1: string;
  addressLine2: string;
  balanceDue: number;
  blocked: string;
  city: string;
  country: string;
  creditLimit: number;
  currencyCode: string;
  currencyId: string;
  displayName: string;
  email: string;
  id: string;
  lastModifiedDateTime: string;
  number: string;
  paymentMethodId: string;
  paymentTermsId: string;
  phoneNumber: string;
  postalCode: string;
  salespersonCode: string;
  shipmentMethodId: string;
  state: string;
  taxAreaDisplayName: string;
  taxAreaId: string;
  taxLiable: boolean;
  taxRegistrationNumber: string;
  type: string;
  website: string;
};

export type NewCustomerRequest = {
  displayName: string;
  type: string;
  addressLine1: string;
  addressLine2: string;
  city: string;
  state: string;
  country: string;
  postalCode: string;
  phoneNumber: string;
  email: string;
  website: string;
  taxLiable: true;
  taxAreaId: string;
  taxRegistrationNumber: string;
  currencyId: string;
  currencyCode: string;
  paymentTermsId: string;
  shipmentMethodId: string;
  paymentMethodId: string;
  blocked: string;
};
